<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <UserSecretsId>aspnet-JubeUI-1585BC54-1CED-470E-AC35-2C7E8B27EE1F</UserSecretsId>
        <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AsyncFixer" Version="1.6.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AutoMapper" Version="15.1.3"/>
        <PackageReference Include="FluentValidation" Version="10.3.6"/>
        <PackageReference Include="Isopoh.Cryptography.Argon2" Version="1.1.12"/>
        <PackageReference Include="linq2db" Version="3.6.0"/>
        <PackageReference Include="linq2db.AspNet" Version="3.6.0"/>
        <PackageReference Include="log4net" Version="3.3.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.14"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.18"/>
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="9.0.13"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.13"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.10.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.10.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.10.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.10.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="6.0.0"/>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0"/>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5"/>
        <PackageReference Include="RabbitMQ.Client" Version="6.2.1"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.2.3"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.2.3"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Pages\Index.en.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Index.en.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Shared\_Layout.en.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>_Layout.en.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Pages\Shared\_Layout.en.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>_Layout.en.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Pages\Index.en.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Index.en.resx</DependentUpon>
        </Compile>

        <Compile Update="Resources\Shared\_Layout.en.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Layout.en.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Jube.ApiTokensCache\Jube.ApiTokensCache.csproj"/>
        <ProjectReference Include="..\Jube.Cache\Jube.Cache.csproj"/>
        <ProjectReference Include="..\Jube.Data\Jube.Data.csproj"/>
        <ProjectReference Include="..\Jube.DynamicEnvironment\Jube.DynamicEnvironment.csproj"/>
        <ProjectReference Include="..\Jube.Dto\Jube.Dto.csproj"/>
        <ProjectReference Include="..\Jube.Engine\Jube.Engine.csproj"/>
        <ProjectReference Include="..\Jube.HttpHeaders\Jube.HttpHeaders.csproj"/>
        <ProjectReference Include="..\Jube.Migrations\Jube.Migrations.csproj"/>
        <ProjectReference Include="..\Jube.Parser\Jube.Parser.csproj"/>
        <ProjectReference Include="..\Jube.Preservation\Jube.Preservation.csproj"/>
        <ProjectReference Include="..\Jube.Mfa\Jube.Mfa.csproj"/>
        <ProjectReference Include="..\Jube.Service\Jube.Service.csproj"/>
        <ProjectReference Include="..\Jube.TaskCancellation\Jube.TaskCancellation.csproj"/>
        <ProjectReference Include="..\Jube.Validations\Jube.Validations.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Jube.environment">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="wwwroot\images"/>
        <Folder Include="wwwroot\js\signalr"/>
    </ItemGroup>

</Project>