<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Jube.DynamicEnvironment\Jube.DynamicEnvironment.csproj"/>
        <ProjectReference Include="..\Jube.Tokenisation\Jube.Tokenisation.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="log4net">
            <HintPath>..\..\..\.nuget\packages\log4net\2.0.14\lib\netstandard2.0\log4net.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Context\"/>
    </ItemGroup>

</Project>
