/* Copyright (C) 2022-present Jube Holdings Limited.
 *
 * This file is part of Jube™ software.
 *
 * Jube™ is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Jube™ is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License along with Jube™. If not,
 * see <https://www.gnu.org/licenses/>.
 */

using System.ComponentModel;
using Jube.Dto.Forms;
using Jube.Dto.Interfaces;

// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace Jube.Dto.ExhaustiveSearchInstance
{
    [FormEndpoint("ExhaustiveSearchInstance")]
    [FormKeys(Id = nameof(Id), Parent = nameof(EntityAnalysisModelId), NaturalKey = nameof(Name))]
    [LockField(nameof(Locked))]
    [FormGroup("Identity", Order = 10)]
    [FormGroup("Anomaly Detection", Order = 20)]
    [FormGroup("Training Data Filter", Order = 30)]
    [FormGroup("Output", Order = 40)]
    [FormGroup("Training Status", Order = 50, Collapsed = true)]
    [FormGroup("Audit", Order = 90, Collapsed = true)]
    public class ExhaustiveSearchInstanceDto : IUpdated, IActivatable, ILockable, ITreeChild, IGuidIdentified
    {
        [Description("Identifier of the Model this Exhaustive Adaptation is registered against. Set from the " +
                     "parent Model context; not user-editable.")]
        public int EntityAnalysisModelId { get; set; }

        [Description("Display name of this Exhaustive Adaptation. Unique within the Model (case-insensitive).")]
        [FormField(Group = "Identity", Order = 10)]
        [ListColumn(Order = 10, Title = "Name")]
        public string? Name { get; set; }

        [Description("When true, this Exhaustive Adaptation participates in evaluation on transaction " +
                     "invocation once trained.")]
        [FormField(Group = "Identity", Order = 20, Widget = "switch")]
        [NewDefault(false)]
        public bool Active { get; set; }

        [Description("When true, this Exhaustive Adaptation is locked and cannot be edited or deleted. Also " +
                     "set implicitly once training has started -- an Exhaustive Adaptation can only be edited " +
                     "while its training StatusId is still 'Awaiting Server' (0).")]
        [FormField(Group = "Identity", Order = 30, Widget = "switch")]
        [NewDefault(false)]
        public bool Locked { get; set; }

        [Description("When true, a One Class Support Vector Machine Anomaly Detection model is trained and " +
                     "used to derive the positive/negative class for supervised learning, in place of (or " +
                     "alongside) a Training Data Filter.")]
        [FormField(Group = "Anomaly Detection", Order = 10, Widget = "switch")]
        [NewDefault(false)]
        public bool Anomaly { get; set; }

        [Description("The probability threshold below which the Anomaly Detection model classifies an example " +
                     "as positive class. Required when Anomaly is true.")]
        [FormField(Group = "Anomaly Detection", Order = 20, Widget = "number")]
        [VisibleWhen(nameof(Anomaly), true)]
        [RequiredWhen(nameof(Anomaly), true)]
        public double AnomalyProbability { get; set; }

        [Description("When true, positive class for supervised learning is instead defined by filtering the " +
                     "Archive table with FilterSql -- a match on the filter is positive class, and the filter " +
                     "is also used to negate the sample of negative class.")]
        [FormField(Group = "Training Data Filter", Order = 10, Widget = "switch")]
        [NewDefault(false)]
        public bool Filter { get; set; }

        [Description("The Query Builder JSON definition backing FilterSql. Required when Filter is true.")]
        [FormField(Group = "Training Data Filter", Order = 20)]
        [VisibleWhen(nameof(Filter), true)]
        [RequiredWhen(nameof(Filter), true)]
        [Forms.Editor("ExhaustiveFilterBuilder")]
        public string? FilterJson { get; set; }

        [Description("The compiled SQL predicate, derived from FilterJson, applied to the Archive table to " +
                     "define positive class. Required when Filter is true. Not directly user-edited -- " +
                     "generated by the Training Data Filter builder.")]
        [FormField(Group = "Training Data Filter", Order = 30, ReadOnly = true)]
        [VisibleWhen(nameof(Filter), true)]
        [RequiredWhen(nameof(Filter), true)]
        public string? FilterSql { get; set; }

        [Description("The SQL parameter tokens for FilterSql, derived from FilterJson. Required when Filter is " +
                     "true. Not directly user-edited -- generated by the Training Data Filter builder.")]
        [FormField(Group = "Training Data Filter", Order = 40, ReadOnly = true)]
        [VisibleWhen(nameof(Filter), true)]
        [RequiredWhen(nameof(Filter), true)]
        public string? FilterTokens { get; set; }

        [Description("When true, every recall of this Exhaustive Adaptation is persisted to the reporting " +
                     "table for later analysis.")]
        [FormField(Group = "Output", Order = 10, Widget = "switch")]
        [NewDefault(false)]
        public bool ReportTable { get; set; }

        [Description("Whether the response payload is returned for a recall of this Exhaustive Adaptation.")]
        [FormField(Group = "Output", Order = 20, Widget = "switch")]
        [NewDefault(false)]
        public bool ResponsePayload { get; set; }

        [Description("Server-assigned globally-unique identifier for this Exhaustive Adaptation, usable for " +
                     "direct HTTP recall of the trained model once training has completed. Read-only.")]
        [FormField(Group = "Training Status", Order = 10, ReadOnly = true)]
        public Guid Guid { get; set; }

        [Description("Server-managed training progress status. 0 Awaiting Server, 1 Query for base case data, " +
                     "2 Calculating Statistics for base case, 3 Normalising Data for unsupervised learning, " +
                     "4 Unsupervised training, 5 Unsupervised training recall, 6 Unsupervised training " +
                     "statistics creation, 7 Query for class filter data, 8 Statistics for class filter data, " +
                     "9 Shuffling data, 10 Normalising data, 11 Over/Symmetric Sampling, 12 Storing final data, " +
                     "13 Correlation analysis, 14 Multicollinearity analysis, 15 Supervised Learning, " +
                     "16 Finished, 17 Finished no class available, 18 Stopping, 19 Stopped. An Exhaustive " +
                     "Adaptation can only be edited while this is 0. Read-only.")]
        [FormField(Group = "Training Status", Order = 20, ReadOnly = true)]
        public byte StatusId { get; set; }

        [Description("Server-managed count of Neural Network topologies attempted so far during evolution. " +
                     "Read-only.")]
        [FormField(Group = "Training Status", Order = 30, ReadOnly = true)]
        public int Models { get; set; }

        [Description("Server-managed count of topologies tried since the last promoted (best-scoring) " +
                     "topology. Training terminates once this exceeds the configured threshold. Read-only.")]
        [FormField(Group = "Training Status", Order = 40, ReadOnly = true)]
        public int ModelsSinceBest { get; set; }

        [Description("Server-managed score of the best topology promoted so far during evolution. Read-only.")]
        [FormField(Group = "Training Status", Order = 50, ReadOnly = true)]
        public double Score { get; set; }

        [Description("Server-managed topology complexity of the best topology promoted so far. Read-only.")]
        [FormField(Group = "Training Status", Order = 60, ReadOnly = true)]
        public double TopologyComplexity { get; set; }

        [Description("Timestamp (UTC) training completed, if applicable. Server-assigned. Read-only.")]
        [FormField(Group = "Training Status", Order = 70, ReadOnly = true, Widget = "date")]
        public DateTimeOffset? CompletedDate { get; set; }

        [Description("Server-assigned row identifier. Read-only.")]
        [FormField(Group = "Audit", Order = 10, ReadOnly = true)]
        [ListColumn(Hidden = true)]
        public int Id { get; set; }

        [Description("User who created this Exhaustive Adaptation. Server-assigned. Read-only. Note: also " +
                     "re-assigned to the acting user on every update -- see the migration report.")]
        [FormField(Group = "Audit", Order = 20, ReadOnly = true)]
        public string? CreatedUser { get; set; }

        [Description("Timestamp (UTC) this Exhaustive Adaptation was created. Server-assigned. Read-only. " +
                     "Note: also reset to the update time on every update -- see the migration report.")]
        [FormField(Group = "Audit", Order = 30, ReadOnly = true, Widget = "date")]
        public DateTimeOffset? CreatedDate { get; set; }

        [Description("Not populated -- the underlying table has no corresponding column. Always null. See the " +
                     "migration report.")]
        [FormField(Group = "Audit", Order = 40, ReadOnly = true)]
        public string? UpdatedUser { get; set; }

        [Description("Timestamp (UTC) this Exhaustive Adaptation was last updated. Server-assigned. Read-only.")]
        [FormField(Group = "Audit", Order = 50, ReadOnly = true, Widget = "date")]
        public DateTimeOffset? UpdatedDate { get; set; }

        [Description("Server-assigned optimistic-concurrency version number, incremented on every update. " +
                     "Read-only.")]
        [FormField(Group = "Audit", Order = 60, ReadOnly = true)]
        [ListColumn(Hidden = true)]
        public int Version { get; set; }

        [Description("User who deleted this Exhaustive Adaptation, if soft-deleted. Server-assigned. " +
                     "Read-only.")]
        [FormField(Group = "Audit", Order = 70, ReadOnly = true)]
        public string? DeletedUser { get; set; }

        [Description("Timestamp (UTC) this Exhaustive Adaptation was soft-deleted, if applicable. " +
                     "Server-assigned. Read-only. Note: the underlying column is non-nullable, so a row that " +
                     "has never been deleted reports 0001-01-01 rather than null -- see the migration report.")]
        [FormField(Group = "Audit", Order = 80, ReadOnly = true, Widget = "date")]
        public DateTimeOffset? DeletedDate { get; set; }
    }
}
