<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AsyncFixer" Version="1.6.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MessagePack" Version="3.1.7"/>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Extensions\System.Char\System.Char\"/>
        <Folder Include="Extensions\System.Char\_CoreObject\"/>
        <Folder Include="Extensions\System.DateTime\System.TimeZoneInfo\"/>
        <Folder Include="Extensions\System.DateTime\System.TimeZone\"/>
        <Folder Include="Extensions\System.DateTime\ToDateTimeFormat\"/>
        <Folder Include="Extensions\System.DateTime\_CoreObject\"/>
        <Folder Include="Extensions\System.Double\System.DateTime\"/>
        <Folder Include="Extensions\System.Double\System.Double\"/>
        <Folder Include="Extensions\System.Double\System.Math\"/>
        <Folder Include="Extensions\System.Double\System.TimeSpan\"/>
        <Folder Include="Extensions\System.Double\_CoreObject\"/>
        <Folder Include="Extensions\System.Int32\GenericInt\"/>
        <Folder Include="Extensions\System.Int32\System.BitConverter\"/>
        <Folder Include="Extensions\System.Int32\System.Char\"/>
        <Folder Include="Extensions\System.Int32\System.DateTime\"/>
        <Folder Include="Extensions\System.Int32\System.Drawing.ColorTranslator\"/>
        <Folder Include="Extensions\System.Int32\System.Drawing.Color\"/>
        <Folder Include="Extensions\System.Int32\System.Math\"/>
        <Folder Include="Extensions\System.Int32\System.Net.IPAddress\"/>
        <Folder Include="Extensions\System.Int32\_CoreObject\"/>
        <Folder Include="Extensions\System.String\Serialization\"/>
        <Folder Include="Extensions\System.String\System.Char\"/>
        <Folder Include="Extensions\System.String\System.String\"/>
        <Folder Include="Extensions\System.String\System.Text.RegularExpressions.Regex\"/>
        <Folder Include="Extensions\System.String\System.Web.HttpUtility\"/>
        <Folder Include="Extensions\System.String\zzzRegexPattern\"/>
        <Folder Include="Extensions\System.String\_CoreObject\"/>
        <Folder Include="Extensions\System.String\_ExtractValueType\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Extensions\System.Boolean\Boolean.IfFalse.cs"/>
        <Compile Remove="Extensions\System.Char\Char.Repeat.cs"/>
        <Compile Remove="Extensions\System.Char\Char.To.cs"/>
        <Compile Remove="Extensions\System.Char\System.Char\Char.ToLower.cs"/>
        <Compile Remove="Extensions\System.Char\System.Char\Char.ToLowerInvariant.cs"/>
        <Compile Remove="Extensions\System.Char\System.Char\Char.ToString.cs"/>
        <Compile Remove="Extensions\System.Char\System.Char\Char.ToUpper.cs"/>
        <Compile Remove="Extensions\System.Char\System.Char\Char.ToUpperInvariant.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.Age.cs"/>
        <Compile Remove="Extensions\System.DateTime\_CoreObject\DateTime.Between.cs"/>
        <Compile Remove="Extensions\System.DateTime\System.TimeZoneInfo\DateTime.ConvertTime.cs"/>
        <Compile Remove="Extensions\System.DateTime\System.TimeZoneInfo\DateTime.ConvertTimeBySystemTimeZoneId.cs"/>
        <Compile Remove="Extensions\System.DateTime\System.TimeZoneInfo\DateTime.ConvertTimeFromUtc.cs"/>
        <Compile Remove="Extensions\System.DateTime\System.TimeZoneInfo\DateTime.ConvertTimeToUtc.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.Elapsed.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.EndOfDay.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.EndOfMonth.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.EndOfWeek.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.EndOfYear.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.FirstDayOfWeek.cs"/>
        <Compile Remove="Extensions\System.DateTime\_CoreObject\DateTime.In.cs"/>
        <Compile Remove="Extensions\System.DateTime\_CoreObject\DateTime.InRange.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsAfternoon.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsDateEqual.cs"/>
        <Compile Remove="Extensions\System.DateTime\System.TimeZone\DateTime.IsDaylightSavingTime.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsFuture.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsMorning.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsNow.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsPast.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsTimeEqual.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsToday.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsWeekDay.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.IsWeekendDay.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.LastDayOfWeek.cs"/>
        <Compile Remove="Extensions\System.DateTime\_CoreObject\DateTime.NotIn.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.SetTime.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.StartOfDay.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.StartOfMonth.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.StartOfWeek.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.StartOfYear.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.ToEpochTimeSpan.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToFullDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToLongDateShortTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToLongDateString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToLongDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToLongTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToMonthDayString.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.Tomorrow.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToRFC1123String.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToShortDateLongTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToShortDateString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToShortDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToShortTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToSortableDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToUniversalSortableDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToUniversalSortableLongDateTimeString.cs"/>
        <Compile Remove="Extensions\System.DateTime\ToDateTimeFormat\DateTime.ToYearMonthString.cs"/>
        <Compile Remove="Extensions\System.DateTime\DateTime.Yesterday.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Abs.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Acos.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Asin.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Atan.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Atan2.cs"/>
        <Compile Remove="Extensions\System.Double\_CoreObject\Double.Between.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Ceiling.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Cos.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Cosh.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Exp.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Floor.cs"/>
        <Compile Remove="Extensions\System.Double\System.TimeSpan\Double.FromDays.cs"/>
        <Compile Remove="Extensions\System.Double\System.TimeSpan\Double.FromHours.cs"/>
        <Compile Remove="Extensions\System.Double\System.TimeSpan\Double.FromMilliseconds.cs"/>
        <Compile Remove="Extensions\System.Double\System.TimeSpan\Double.FromMinutes.cs"/>
        <Compile Remove="Extensions\System.Double\System.DateTime\Double.FromOADate.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.IEEERemainder.cs"/>
        <Compile Remove="Extensions\System.Double\_CoreObject\Double.In.cs"/>
        <Compile Remove="Extensions\System.Double\_CoreObject\Double.InRange.cs"/>
        <Compile Remove="Extensions\System.Double\System.Double\Double.IsInfinity.cs"/>
        <Compile Remove="Extensions\System.Double\System.Double\Double.IsNaN.cs"/>
        <Compile Remove="Extensions\System.Double\System.Double\Double.IsNegativeInfinity.cs"/>
        <Compile Remove="Extensions\System.Double\System.Double\Double.IsPositiveInfinity.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Log.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Log10.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Max.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Min.cs"/>
        <Compile Remove="Extensions\System.Double\_CoreObject\Double.NotIn.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Pow.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Round.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Sign.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Sin.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Sinh.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Sqrt.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Tan.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Tanh.cs"/>
        <Compile Remove="Extensions\System.Double\Double.ToMoney.cs"/>
        <Compile Remove="Extensions\System.Double\System.Math\Double.Truncate.cs"/>
        <Compile Remove="Extensions\System.Int32\Int.SqlSystemTypeToSqlDbType.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.Abs.cs"/>
        <Compile Remove="Extensions\System.Int32\_CoreObject\Int32.Between.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.BigMul.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Char\Int32.ConvertFromUtf32.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.Days.cs"/>
        <Compile Remove="Extensions\System.Int32\System.DateTime\Int32.DaysInMonth.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.DivRem.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.FactorOf.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Drawing.Color\Int32.FromArgb.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Drawing.ColorTranslator\Int32.FromOle.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Drawing.ColorTranslator\Int32.FromWin32.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Net.IPAddress\Int32.HostToNetworkOrder.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.Hours.cs"/>
        <Compile Remove="Extensions\System.Int32\_CoreObject\Int32.In.cs"/>
        <Compile Remove="Extensions\System.Int32\_CoreObject\Int32.InRange.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.IsEven.cs"/>
        <Compile Remove="Extensions\System.Int32\System.DateTime\Int32.IsLeapYear.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.IsMultipleOf.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.IsOdd.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.IsPrime.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.Max.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.Milliseconds.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.Min.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.Minutes.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Net.IPAddress\Int32.NetworkToHostOrder.cs"/>
        <Compile Remove="Extensions\System.Int32\GenericInt\Int32.Seconds.cs"/>
        <Compile Remove="Extensions\System.Int32\System.Math\Int32.Sign.cs"/>
        <Compile Remove="Extensions\System.String\String.Br2Nl.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.CompareOrdinal.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.Concat.cs"/>
        <Compile Remove="Extensions\System.String\String.Concatenate.cs"/>
        <Compile Remove="Extensions\System.String\String.ConcatWith.cs"/>
        <Compile Remove="Extensions\System.String\String.Contains.cs"/>
        <Compile Remove="Extensions\System.String\String.ContainsAll.cs"/>
        <Compile Remove="Extensions\System.String\String.ContainsAny.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.ConvertToUtf32.cs"/>
        <Compile Remove="Extensions\System.String\String.DecodeBase64.cs"/>
        <Compile Remove="Extensions\System.String\Serialization\String.DeserializeJson.cs"/>
        <Compile Remove="Extensions\System.String\String.EncodeBase64.cs"/>
        <Compile Remove="Extensions\System.String\String.EqualsIgnoreCase.cs"/>
        <Compile Remove="Extensions\System.String\String.EscapeXml.cs"/>
        <Compile Remove="Extensions\System.String\String.Extract.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractDecimal.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractDouble.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractInt16.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractInt32.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractInt64.cs"/>
        <Compile Remove="Extensions\System.String\String.ExtractLetter.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyDecimal.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyDouble.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyInt16.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyInt32.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyInt64.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyUInt16.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyUInt32.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractManyUInt64.cs"/>
        <Compile Remove="Extensions\System.String\String.ExtractNumber.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractUInt16.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractUInt32.cs"/>
        <Compile Remove="Extensions\System.String\_ExtractValueType\String.ExtractUInt64.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.Format.cs"/>
        <Compile Remove="Extensions\System.String\String.FormatWith.cs"/>
        <Compile Remove="Extensions\System.String\String.GetAfter.cs"/>
        <Compile Remove="Extensions\System.String\String.GetBefore.cs"/>
        <Compile Remove="Extensions\System.String\String.GetBetween.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.GetNumericValue.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.GetUnicodeCategory.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.HtmlAttributeEncode.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.HtmlDecode.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.HtmlEncode.cs"/>
        <Compile Remove="Extensions\System.String\String.IfEmpty.cs"/>
        <Compile Remove="Extensions\System.String\_CoreObject\String.In.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.Intern.cs"/>
        <Compile Remove="Extensions\System.String\String.IsAlpha.cs"/>
        <Compile Remove="Extensions\System.String\String.IsAlphaNumeric.cs"/>
        <Compile Remove="Extensions\System.String\String.IsAnagram.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsControl.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsDigit.cs"/>
        <Compile Remove="Extensions\System.String\String.IsEmpty.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsHighSurrogate.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.IsInterned.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsLetter.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsLetterOrDigit.cs"/>
        <Compile Remove="Extensions\System.String\String.IsLike.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsLower.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsLowSurrogate.cs"/>
        <Compile Remove="Extensions\System.String\System.Text.RegularExpressions.Regex\String.IsMatch.cs"/>
        <Compile Remove="Extensions\System.String\String.IsNotEmpty.cs"/>
        <Compile Remove="Extensions\System.String\_CoreObject\String.IsNotNull.cs"/>
        <Compile Remove="Extensions\System.String\String.IsNotNullOrEmpty.cs"/>
        <Compile Remove="Extensions\System.String\String.IsNotNullOrWhiteSpace.cs"/>
        <Compile Remove="Extensions\System.String\_CoreObject\String.IsNull.cs"/>
        <Compile Remove="Extensions\System.String\String.IsNullOrEmpty.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.IsNullOrWhiteSpace.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsNumber.cs"/>
        <Compile Remove="Extensions\System.String\String.IsNumeric.cs"/>
        <Compile Remove="Extensions\System.String\String.IsPalindrome.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsPunctuation.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsSeparator.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsSurrogate.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsSurrogatePair.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsSymbol.cs"/>
        <Compile Remove="Extensions\System.String\System.Char\String.IsUpper.cs"/>
        <Compile Remove="Extensions\System.String\zzzRegexPattern\String.IsValidEmail.cs"/>
        <Compile Remove="Extensions\System.String\zzzRegexPattern\String.IsValidIP.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.JavaScriptStringEncode.cs"/>
        <Compile Remove="Extensions\System.String\System.String\String.Join.cs"/>
        <Compile Remove="Extensions\System.String\String.Left.cs"/>
        <Compile Remove="Extensions\System.String\String.LeftSafe.cs"/>
        <Compile Remove="Extensions\System.String\System.Text.RegularExpressions.Regex\String.Match.cs"/>
        <Compile Remove="Extensions\System.String\System.Text.RegularExpressions.Regex\String.Matches.cs"/>
        <Compile Remove="Extensions\System.String\String.Nl2Br.cs"/>
        <Compile Remove="Extensions\System.String\_CoreObject\String.NotIn.cs"/>
        <Compile Remove="Extensions\System.String\String.NullIfEmpty.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.ParseQueryString.cs"/>
        <Compile Remove="Extensions\System.String\String.PathCombine.cs"/>
        <Compile Remove="Extensions\System.String\String.RemoveDiacritics.cs"/>
        <Compile Remove="Extensions\System.String\String.RemoveLetter.cs"/>
        <Compile Remove="Extensions\System.String\String.RemoveNumber.cs"/>
        <Compile Remove="Extensions\System.String\String.RemoveWhere.cs"/>
        <Compile Remove="Extensions\System.String\String.Repeat.cs"/>
        <Compile Remove="Extensions\System.String\String.Replace.cs"/>
        <Compile Remove="Extensions\System.String\String.ReplaceByEmpty.cs"/>
        <Compile Remove="Extensions\System.String\String.ReplaceFirst.cs"/>
        <Compile Remove="Extensions\System.String\String.ReplaceLast.cs"/>
        <Compile Remove="Extensions\System.String\String.ReplaceWhenEquals.cs"/>
        <Compile Remove="Extensions\System.String\String.Reverse.cs"/>
        <Compile Remove="Extensions\System.String\String.Right.cs"/>
        <Compile Remove="Extensions\System.String\String.RightSafe.cs"/>
        <Compile Remove="Extensions\System.String\String.SaveAs.cs"/>
        <Compile Remove="Extensions\System.String\String.Split.cs"/>
        <Compile Remove="Extensions\System.String\String.ToByteArray.cs"/>
        <Compile Remove="Extensions\System.String\String.ToEnum.cs"/>
        <Compile Remove="Extensions\System.String\String.ToTitleCase.cs"/>
        <Compile Remove="Extensions\System.String\String.ToValidDateTimeOrNull.cs"/>
        <Compile Remove="Extensions\System.String\String.ToXDocument.cs"/>
        <Compile Remove="Extensions\System.String\String.ToXmlDocument.cs"/>
        <Compile Remove="Extensions\System.String\String.Truncate.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.UrlDecode.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.UrlDecodeToBytes.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.UrlEncode.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.UrlEncodeToBytes.cs"/>
        <Compile Remove="Extensions\System.String\System.Web.HttpUtility\String.UrlPathEncode.cs"/>
    </ItemGroup>

</Project>
